"""fix models UUIDs

Revision ID: dc184ce32624
Revises:
Create Date: 2025-12-02 12:38:33.371350

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "dc184ce32624"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
